// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsMessages(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashMessages(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsMessages(lhsKey, rhsKey) {
          if deepEqualsMessages(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsMessages(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashMessages(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashMessages(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashMessages(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashMessages(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashMessages(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Reachability of the paired wearable/phone counterpart.
enum ConnectionStateDto: Int {
  /// Platform stack unavailable (no Play Services / WCSession unsupported).
  case unsupported = 0
  /// No counterpart device is paired.
  case unpaired = 1
  /// Paired, companion app not installed on the counterpart.
  case appNotInstalled = 2
  /// Paired and installed, but not currently reachable (e.g. Bluetooth off).
  case unreachable = 3
  /// Counterpart is reachable for interactive messages.
  case reachable = 4
}

/// How an event crossed the boundary.
enum WearerEventKindDto: Int {
  /// Interactive message.
  case message = 0
  /// Synced or transferred data.
  case data = 1
  /// A file received via transferFile. `filePath` points at the local copy.
  case file = 2
}

/// How (whether) this device can launch the companion app.
enum CompanionLaunchDto: Int {
  /// RemoteActivityHelper: opens the companion in the foreground.
  case foreground = 0
  /// HealthKit workout session only (iOS -> watchOS).
  case workoutOnly = 1
  /// The OS offers no way to launch the counterpart app.
  case none = 2
}

/// Snapshot of the companion relationship.
///
/// Generated class from Pigeon that represents data sent in messages.
struct CompanionStatusDto: Hashable {
  var state: ConnectionStateDto
  /// Reachable node ids (Android may have several; iOS has at most one).
  var nodes: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CompanionStatusDto? {
    let state = pigeonVar_list[0] as! ConnectionStateDto
    let nodes = pigeonVar_list[1] as! [String]

    return CompanionStatusDto(
      state: state,
      nodes: nodes
    )
  }
  func toList() -> [Any?] {
    return [
      state,
      nodes,
    ]
  }
  static func == (lhs: CompanionStatusDto, rhs: CompanionStatusDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.state, rhs.state) && deepEqualsMessages(lhs.nodes, rhs.nodes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CompanionStatusDto")
    deepHashMessages(value: state, hasher: &hasher)
    deepHashMessages(value: nodes, hasher: &hasher)
  }
}

/// A message or data event crossing the device boundary.
///
/// Generated class from Pigeon that represents data sent in messages.
struct WearerEventDto: Hashable {
  /// Unique id for at-least-once dedup across background replays.
  var id: String
  var kind: WearerEventKindDto
  /// Application-defined routing path, e.g. '/workout/update'.
  var path: String
  var payload: FlutterStandardTypedData
  var sourceNodeId: String
  var timestampMillis: Int64
  /// True when the event was received while no Flutter engine was attached
  /// and is being replayed from the persistent queue.
  var deliveredWhileDead: Bool
  /// For [WearerEventKindDto.file] events: absolute path of the received
  /// file (stored in the app's cache directory). Null for other kinds.
  var filePath: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WearerEventDto? {
    let id = pigeonVar_list[0] as! String
    let kind = pigeonVar_list[1] as! WearerEventKindDto
    let path = pigeonVar_list[2] as! String
    let payload = pigeonVar_list[3] as! FlutterStandardTypedData
    let sourceNodeId = pigeonVar_list[4] as! String
    let timestampMillis = pigeonVar_list[5] as! Int64
    let deliveredWhileDead = pigeonVar_list[6] as! Bool
    let filePath: String? = nilOrValue(pigeonVar_list[7])

    return WearerEventDto(
      id: id,
      kind: kind,
      path: path,
      payload: payload,
      sourceNodeId: sourceNodeId,
      timestampMillis: timestampMillis,
      deliveredWhileDead: deliveredWhileDead,
      filePath: filePath
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      kind,
      path,
      payload,
      sourceNodeId,
      timestampMillis,
      deliveredWhileDead,
      filePath,
    ]
  }
  static func == (lhs: WearerEventDto, rhs: WearerEventDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.id, rhs.id) && deepEqualsMessages(lhs.kind, rhs.kind) && deepEqualsMessages(lhs.path, rhs.path) && deepEqualsMessages(lhs.payload, rhs.payload) && deepEqualsMessages(lhs.sourceNodeId, rhs.sourceNodeId) && deepEqualsMessages(lhs.timestampMillis, rhs.timestampMillis) && deepEqualsMessages(lhs.deliveredWhileDead, rhs.deliveredWhileDead) && deepEqualsMessages(lhs.filePath, rhs.filePath)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WearerEventDto")
    deepHashMessages(value: id, hasher: &hasher)
    deepHashMessages(value: kind, hasher: &hasher)
    deepHashMessages(value: path, hasher: &hasher)
    deepHashMessages(value: payload, hasher: &hasher)
    deepHashMessages(value: sourceNodeId, hasher: &hasher)
    deepHashMessages(value: timestampMillis, hasher: &hasher)
    deepHashMessages(value: deliveredWhileDead, hasher: &hasher)
    deepHashMessages(value: filePath, hasher: &hasher)
  }
}

/// What this device/pairing actually supports. Static OS facts plus the
/// dynamic ones (e.g. HealthKit availability); honest, never aspirational.
///
/// Generated class from Pigeon that represents data sent in messages.
struct WearerCapabilitiesDto: Hashable {
  var message: Bool
  var request: Bool
  var syncData: Bool
  var transferData: Bool
  var transferFile: Bool
  /// Bidirectional streams: native ChannelClient streams on Android,
  /// sendMessage-framed emulation on iOS (needs a reachable counterpart).
  var stream: Bool
  var companionLaunch: CompanionLaunchDto
  /// transferCurrentComplicationUserInfo (iOS only).
  var complicationPush: Bool
  /// Tile/complication re-render requests (Wear OS only).
  var surfaceUpdate: Bool
  /// Events delivered while the app is killed (listener service /
  /// WatchConnectivity background launch).
  var backgroundWake: Bool
  /// Safe upper bound for a single sendMessage/sendRequest payload.
  /// transferData has no limit (large payloads route through a file).
  var maxMessageBytes: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WearerCapabilitiesDto? {
    let message = pigeonVar_list[0] as! Bool
    let request = pigeonVar_list[1] as! Bool
    let syncData = pigeonVar_list[2] as! Bool
    let transferData = pigeonVar_list[3] as! Bool
    let transferFile = pigeonVar_list[4] as! Bool
    let stream = pigeonVar_list[5] as! Bool
    let companionLaunch = pigeonVar_list[6] as! CompanionLaunchDto
    let complicationPush = pigeonVar_list[7] as! Bool
    let surfaceUpdate = pigeonVar_list[8] as! Bool
    let backgroundWake = pigeonVar_list[9] as! Bool
    let maxMessageBytes = pigeonVar_list[10] as! Int64

    return WearerCapabilitiesDto(
      message: message,
      request: request,
      syncData: syncData,
      transferData: transferData,
      transferFile: transferFile,
      stream: stream,
      companionLaunch: companionLaunch,
      complicationPush: complicationPush,
      surfaceUpdate: surfaceUpdate,
      backgroundWake: backgroundWake,
      maxMessageBytes: maxMessageBytes
    )
  }
  func toList() -> [Any?] {
    return [
      message,
      request,
      syncData,
      transferData,
      transferFile,
      stream,
      companionLaunch,
      complicationPush,
      surfaceUpdate,
      backgroundWake,
      maxMessageBytes,
    ]
  }
  static func == (lhs: WearerCapabilitiesDto, rhs: WearerCapabilitiesDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.message, rhs.message) && deepEqualsMessages(lhs.request, rhs.request) && deepEqualsMessages(lhs.syncData, rhs.syncData) && deepEqualsMessages(lhs.transferData, rhs.transferData) && deepEqualsMessages(lhs.transferFile, rhs.transferFile) && deepEqualsMessages(lhs.stream, rhs.stream) && deepEqualsMessages(lhs.companionLaunch, rhs.companionLaunch) && deepEqualsMessages(lhs.complicationPush, rhs.complicationPush) && deepEqualsMessages(lhs.surfaceUpdate, rhs.surfaceUpdate) && deepEqualsMessages(lhs.backgroundWake, rhs.backgroundWake) && deepEqualsMessages(lhs.maxMessageBytes, rhs.maxMessageBytes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WearerCapabilitiesDto")
    deepHashMessages(value: message, hasher: &hasher)
    deepHashMessages(value: request, hasher: &hasher)
    deepHashMessages(value: syncData, hasher: &hasher)
    deepHashMessages(value: transferData, hasher: &hasher)
    deepHashMessages(value: transferFile, hasher: &hasher)
    deepHashMessages(value: stream, hasher: &hasher)
    deepHashMessages(value: companionLaunch, hasher: &hasher)
    deepHashMessages(value: complicationPush, hasher: &hasher)
    deepHashMessages(value: surfaceUpdate, hasher: &hasher)
    deepHashMessages(value: backgroundWake, hasher: &hasher)
    deepHashMessages(value: maxMessageBytes, hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ConnectionStateDto(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WearerEventKindDto(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CompanionLaunchDto(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      return CompanionStatusDto.fromList(self.readValue() as! [Any?])
    case 133:
      return WearerEventDto.fromList(self.readValue() as! [Any?])
    case 134:
      return WearerCapabilitiesDto.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ConnectionStateDto {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? WearerEventKindDto {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? CompanionLaunchDto {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? CompanionStatusDto {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? WearerEventDto {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? WearerCapabilitiesDto {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Dart -> native.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol WearerLinkHostApi {
  /// Whether the wearable stack exists on this device at all.
  func isSupported() throws -> Bool
  func getCompanionStatus(completion: @escaping (Result<CompanionStatusDto, Error>) -> Void)
  /// Interactive message. Requires a reachable counterpart.
  /// On Android sends to every reachable capable node, or only [nodeId]
  /// when given; iOS has a single counterpart and ignores [nodeId].
  func sendMessage(path: String, payload: FlutterStandardTypedData, nodeId: String?, completion: @escaping (Result<Void, Error>) -> Void)
  /// Request/response round trip: resolves with the counterpart's reply
  /// payload. Android: MessageClient.sendRequest RPC; iOS: sendMessage
  /// reply payload. The counterpart must have a request handler
  /// (setRequestHandler in Dart, onRequest in WearerLinkWatch); without one
  /// the call fails with 'noHandler'.
  func sendRequest(path: String, payload: FlutterStandardTypedData, nodeId: String?, completion: @escaping (Result<FlutterStandardTypedData, Error>) -> Void)
  /// Persistent state sync: DataClient item (Android) /
  /// updateApplicationContext (iOS). Latest value per path wins.
  func syncData(path: String, payload: FlutterStandardTypedData, completion: @escaping (Result<Void, Error>) -> Void)
  /// Latest value the COUNTERPART synced for [path] (mirror of what
  /// dataEvents delivered), or null if it never synced one.
  func readSyncData(path: String, completion: @escaping (Result<FlutterStandardTypedData?, Error>) -> Void)
  /// Remove the value THIS device synced for [path] (the counterpart's own
  /// value is theirs to delete).
  func deleteSyncData(path: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Queued background transfer that survives unreachability:
  /// DataClient with urgent flag (Android) / transferUserInfo (iOS).
  func transferData(path: String, payload: FlutterStandardTypedData, completion: @escaping (Result<Void, Error>) -> Void)
  /// Launch the companion app on the counterpart device.
  /// Android: RemoteActivityHelper (both directions, foreground).
  /// iOS phone->watch: HealthKit workout launch only; throws
  /// 'unsupported' PlatformException otherwise.
  func launchCompanion(completion: @escaping (Result<Void, Error>) -> Void)
  /// Drain events persisted while the app was dead. Called by the Dart
  /// facade on startup; each drained event is also removed from the store.
  func drainPendingEvents(completion: @escaping (Result<[WearerEventDto], Error>) -> Void)
  /// Transfer the file at [filePath] to the counterpart (or only [nodeId]
  /// on Android). Android: ChannelClient (needs a reachable capable node).
  /// iOS: WCSession.transferFile (queued, survives unreachability).
  func transferFile(path: String, filePath: String, nodeId: String?, completion: @escaping (Result<Void, Error>) -> Void)
  /// Push fresh complication data to the watch face.
  /// iOS: transferCurrentComplicationUserInfo (budgeted by watchOS — ~50/day;
  /// over budget it silently degrades to a regular transfer).
  /// Android: throws 'unsupported' — use syncData + requestSurfaceUpdate
  /// inside the Wear OS app instead.
  func updateComplication(payload: FlutterStandardTypedData, completion: @escaping (Result<Void, Error>) -> Void)
  /// Ask the system to re-render this app's tile or complication after its
  /// backing state changed. Wear OS only (call it inside the watch app);
  /// [component] is the fully-qualified class name of the app's TileService
  /// or complication data-source service. Throws 'unsupported' on iOS.
  func requestSurfaceUpdate(component: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Store the callback handles powering the headless background isolate.
  /// [dispatcherHandle] is the plugin's entrypoint; [userHandle] the app's
  /// top-level handler. Persisted natively so events that arrive while the
  /// app is dead can start a Dart isolate and be handled immediately.
  func registerBackgroundHandler(dispatcherHandle: Int64, userHandle: Int64) throws
  /// Stop launching the background isolate for dead-app events (they fall
  /// back to the persistent queue only).
  func clearBackgroundHandler() throws
  /// What this device/pairing actually supports.
  func getCapabilities() throws -> WearerCapabilitiesDto
  /// While disabled, nothing is delivered to Dart or the background
  /// isolate — every inbound event diverts to the persistent queue (same
  /// path as a killed app; nothing is lost) and incoming streams are
  /// rejected. Persisted across launches.
  func setEventDeliveryEnabled(enabled: Bool) throws
  func isEventDeliveryEnabled() throws -> Bool
  /// Open a bidirectional stream to the counterpart; resolves with the
  /// stream id once the counterpart accepted. Requires a reachable node.
  func openStream(path: String, nodeId: String?, completion: @escaping (Result<String, Error>) -> Void)
  /// Write bytes to an open stream (chunked internally where the transport
  /// needs it). Fails if the stream is closed.
  func sendStreamData(streamId: String, data: FlutterStandardTypedData, completion: @escaping (Result<Void, Error>) -> Void)
  /// Close a stream (both directions). Idempotent.
  func closeStream(streamId: String, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class WearerLinkHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `WearerLinkHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: WearerLinkHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Whether the wearable stack exists on this device at all.
    let isSupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.isSupported\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isSupportedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isSupported()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isSupportedChannel.setMessageHandler(nil)
    }
    let getCompanionStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.getCompanionStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCompanionStatusChannel.setMessageHandler { _, reply in
        api.getCompanionStatus { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getCompanionStatusChannel.setMessageHandler(nil)
    }
    /// Interactive message. Requires a reachable counterpart.
    /// On Android sends to every reachable capable node, or only [nodeId]
    /// when given; iOS has a single counterpart and ignores [nodeId].
    let sendMessageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.sendMessage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendMessageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        let payloadArg = args[1] as! FlutterStandardTypedData
        let nodeIdArg: String? = nilOrValue(args[2])
        api.sendMessage(path: pathArg, payload: payloadArg, nodeId: nodeIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendMessageChannel.setMessageHandler(nil)
    }
    /// Request/response round trip: resolves with the counterpart's reply
    /// payload. Android: MessageClient.sendRequest RPC; iOS: sendMessage
    /// reply payload. The counterpart must have a request handler
    /// (setRequestHandler in Dart, onRequest in WearerLinkWatch); without one
    /// the call fails with 'noHandler'.
    let sendRequestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.sendRequest\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendRequestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        let payloadArg = args[1] as! FlutterStandardTypedData
        let nodeIdArg: String? = nilOrValue(args[2])
        api.sendRequest(path: pathArg, payload: payloadArg, nodeId: nodeIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendRequestChannel.setMessageHandler(nil)
    }
    /// Persistent state sync: DataClient item (Android) /
    /// updateApplicationContext (iOS). Latest value per path wins.
    let syncDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.syncData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      syncDataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        let payloadArg = args[1] as! FlutterStandardTypedData
        api.syncData(path: pathArg, payload: payloadArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      syncDataChannel.setMessageHandler(nil)
    }
    /// Latest value the COUNTERPART synced for [path] (mirror of what
    /// dataEvents delivered), or null if it never synced one.
    let readSyncDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.readSyncData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readSyncDataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        api.readSyncData(path: pathArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readSyncDataChannel.setMessageHandler(nil)
    }
    /// Remove the value THIS device synced for [path] (the counterpart's own
    /// value is theirs to delete).
    let deleteSyncDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.deleteSyncData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteSyncDataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        api.deleteSyncData(path: pathArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      deleteSyncDataChannel.setMessageHandler(nil)
    }
    /// Queued background transfer that survives unreachability:
    /// DataClient with urgent flag (Android) / transferUserInfo (iOS).
    let transferDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.transferData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      transferDataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        let payloadArg = args[1] as! FlutterStandardTypedData
        api.transferData(path: pathArg, payload: payloadArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      transferDataChannel.setMessageHandler(nil)
    }
    /// Launch the companion app on the counterpart device.
    /// Android: RemoteActivityHelper (both directions, foreground).
    /// iOS phone->watch: HealthKit workout launch only; throws
    /// 'unsupported' PlatformException otherwise.
    let launchCompanionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.launchCompanion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      launchCompanionChannel.setMessageHandler { _, reply in
        api.launchCompanion { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      launchCompanionChannel.setMessageHandler(nil)
    }
    /// Drain events persisted while the app was dead. Called by the Dart
    /// facade on startup; each drained event is also removed from the store.
    let drainPendingEventsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.drainPendingEvents\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      drainPendingEventsChannel.setMessageHandler { _, reply in
        api.drainPendingEvents { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      drainPendingEventsChannel.setMessageHandler(nil)
    }
    /// Transfer the file at [filePath] to the counterpart (or only [nodeId]
    /// on Android). Android: ChannelClient (needs a reachable capable node).
    /// iOS: WCSession.transferFile (queued, survives unreachability).
    let transferFileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.transferFile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      transferFileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        let filePathArg = args[1] as! String
        let nodeIdArg: String? = nilOrValue(args[2])
        api.transferFile(path: pathArg, filePath: filePathArg, nodeId: nodeIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      transferFileChannel.setMessageHandler(nil)
    }
    /// Push fresh complication data to the watch face.
    /// iOS: transferCurrentComplicationUserInfo (budgeted by watchOS — ~50/day;
    /// over budget it silently degrades to a regular transfer).
    /// Android: throws 'unsupported' — use syncData + requestSurfaceUpdate
    /// inside the Wear OS app instead.
    let updateComplicationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.updateComplication\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateComplicationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let payloadArg = args[0] as! FlutterStandardTypedData
        api.updateComplication(payload: payloadArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      updateComplicationChannel.setMessageHandler(nil)
    }
    /// Ask the system to re-render this app's tile or complication after its
    /// backing state changed. Wear OS only (call it inside the watch app);
    /// [component] is the fully-qualified class name of the app's TileService
    /// or complication data-source service. Throws 'unsupported' on iOS.
    let requestSurfaceUpdateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.requestSurfaceUpdate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestSurfaceUpdateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let componentArg = args[0] as! String
        api.requestSurfaceUpdate(component: componentArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestSurfaceUpdateChannel.setMessageHandler(nil)
    }
    /// Store the callback handles powering the headless background isolate.
    /// [dispatcherHandle] is the plugin's entrypoint; [userHandle] the app's
    /// top-level handler. Persisted natively so events that arrive while the
    /// app is dead can start a Dart isolate and be handled immediately.
    let registerBackgroundHandlerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.registerBackgroundHandler\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      registerBackgroundHandlerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let dispatcherHandleArg = args[0] as! Int64
        let userHandleArg = args[1] as! Int64
        do {
          try api.registerBackgroundHandler(dispatcherHandle: dispatcherHandleArg, userHandle: userHandleArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      registerBackgroundHandlerChannel.setMessageHandler(nil)
    }
    /// Stop launching the background isolate for dead-app events (they fall
    /// back to the persistent queue only).
    let clearBackgroundHandlerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.clearBackgroundHandler\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearBackgroundHandlerChannel.setMessageHandler { _, reply in
        do {
          try api.clearBackgroundHandler()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearBackgroundHandlerChannel.setMessageHandler(nil)
    }
    /// What this device/pairing actually supports.
    let getCapabilitiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.getCapabilities\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCapabilitiesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getCapabilities()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCapabilitiesChannel.setMessageHandler(nil)
    }
    /// While disabled, nothing is delivered to Dart or the background
    /// isolate — every inbound event diverts to the persistent queue (same
    /// path as a killed app; nothing is lost) and incoming streams are
    /// rejected. Persisted across launches.
    let setEventDeliveryEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.setEventDeliveryEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setEventDeliveryEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setEventDeliveryEnabled(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setEventDeliveryEnabledChannel.setMessageHandler(nil)
    }
    let isEventDeliveryEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.isEventDeliveryEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isEventDeliveryEnabledChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isEventDeliveryEnabled()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isEventDeliveryEnabledChannel.setMessageHandler(nil)
    }
    /// Open a bidirectional stream to the counterpart; resolves with the
    /// stream id once the counterpart accepted. Requires a reachable node.
    let openStreamChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.openStream\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openStreamChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        let nodeIdArg: String? = nilOrValue(args[1])
        api.openStream(path: pathArg, nodeId: nodeIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openStreamChannel.setMessageHandler(nil)
    }
    /// Write bytes to an open stream (chunked internally where the transport
    /// needs it). Fails if the stream is closed.
    let sendStreamDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.sendStreamData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendStreamDataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let streamIdArg = args[0] as! String
        let dataArg = args[1] as! FlutterStandardTypedData
        api.sendStreamData(streamId: streamIdArg, data: dataArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendStreamDataChannel.setMessageHandler(nil)
    }
    /// Close a stream (both directions). Idempotent.
    let closeStreamChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.closeStream\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeStreamChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let streamIdArg = args[0] as! String
        api.closeStream(streamId: streamIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      closeStreamChannel.setMessageHandler(nil)
    }
  }
}
/// Native -> Dart.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol WearerLinkFlutterApiProtocol {
  func onMessage(event eventArg: WearerEventDto, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Request from the counterpart; the returned bytes are its reply.
  /// Completing with an error rejects the request on the sender's side.
  func onRequest(event eventArg: WearerEventDto, completion: @escaping (Result<FlutterStandardTypedData, PigeonError>) -> Void)
  func onDataChanged(event eventArg: WearerEventDto, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onFileReceived(event eventArg: WearerEventDto, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onConnectionStateChanged(status statusArg: CompanionStatusDto, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// A stream was opened — locally initiated (incoming=false, resolves the
  /// pending openStream) or by the counterpart (incoming=true).
  func onStreamOpened(streamId streamIdArg: String, path pathArg: String, sourceNodeId sourceNodeIdArg: String, incoming incomingArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onStreamData(streamId streamIdArg: String, data dataArg: FlutterStandardTypedData, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// The stream ended; [error] is null for an orderly close.
  func onStreamClosed(streamId streamIdArg: String, error errorArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class WearerLinkFlutterApi: WearerLinkFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onMessage(event eventArg: WearerEventDto, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.wearer_link.WearerLinkFlutterApi.onMessage\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Request from the counterpart; the returned bytes are its reply.
  /// Completing with an error rejects the request on the sender's side.
  func onRequest(event eventArg: WearerEventDto, completion: @escaping (Result<FlutterStandardTypedData, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.wearer_link.WearerLinkFlutterApi.onRequest\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(.failure(PigeonError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! FlutterStandardTypedData
        completion(.success(result))
      }
    }
  }
  func onDataChanged(event eventArg: WearerEventDto, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.wearer_link.WearerLinkFlutterApi.onDataChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onFileReceived(event eventArg: WearerEventDto, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.wearer_link.WearerLinkFlutterApi.onFileReceived\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onConnectionStateChanged(status statusArg: CompanionStatusDto, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.wearer_link.WearerLinkFlutterApi.onConnectionStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([statusArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// A stream was opened — locally initiated (incoming=false, resolves the
  /// pending openStream) or by the counterpart (incoming=true).
  func onStreamOpened(streamId streamIdArg: String, path pathArg: String, sourceNodeId sourceNodeIdArg: String, incoming incomingArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.wearer_link.WearerLinkFlutterApi.onStreamOpened\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([streamIdArg, pathArg, sourceNodeIdArg, incomingArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onStreamData(streamId streamIdArg: String, data dataArg: FlutterStandardTypedData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.wearer_link.WearerLinkFlutterApi.onStreamData\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([streamIdArg, dataArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// The stream ended; [error] is null for an orderly close.
  func onStreamClosed(streamId streamIdArg: String, error errorArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.wearer_link.WearerLinkFlutterApi.onStreamClosed\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([streamIdArg, errorArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
/// Dart -> native, background isolate only.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol WearerLinkBackgroundHostApi {
  /// Handshake from the freshly-started background isolate. Returns the raw
  /// callback handle of the user's registered handler; after this returns,
  /// the native side starts delivering queued events.
  func backgroundReady() throws -> Int64
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class WearerLinkBackgroundHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `WearerLinkBackgroundHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: WearerLinkBackgroundHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Handshake from the freshly-started background isolate. Returns the raw
    /// callback handle of the user's registered handler; after this returns,
    /// the native side starts delivering queued events.
    let backgroundReadyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wearer_link.WearerLinkBackgroundHostApi.backgroundReady\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      backgroundReadyChannel.setMessageHandler { _, reply in
        do {
          let result = try api.backgroundReady()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      backgroundReadyChannel.setMessageHandler(nil)
    }
  }
}
/// Native -> Dart, background isolate only. The completion of
/// [onBackgroundEvent] is the delivery ack: the native side removes the
/// event from the persistent queue only after the Dart future completes.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol WearerLinkBackgroundFlutterApiProtocol {
  func onBackgroundEvent(event eventArg: WearerEventDto, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class WearerLinkBackgroundFlutterApi: WearerLinkBackgroundFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onBackgroundEvent(event eventArg: WearerEventDto, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.wearer_link.WearerLinkBackgroundFlutterApi.onBackgroundEvent\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
