// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.crdzbird.wearer_link

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Reachability of the paired wearable/phone counterpart. */
enum class ConnectionStateDto(val raw: Int) {
  /** Platform stack unavailable (no Play Services / WCSession unsupported). */
  UNSUPPORTED(0),
  /** No counterpart device is paired. */
  UNPAIRED(1),
  /** Paired, companion app not installed on the counterpart. */
  APP_NOT_INSTALLED(2),
  /** Paired and installed, but not currently reachable (e.g. Bluetooth off). */
  UNREACHABLE(3),
  /** Counterpart is reachable for interactive messages. */
  REACHABLE(4);

  companion object {
    fun ofRaw(raw: Int): ConnectionStateDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** How an event crossed the boundary. */
enum class WearerEventKindDto(val raw: Int) {
  /** Interactive message. */
  MESSAGE(0),
  /** Synced or transferred data. */
  DATA(1),
  /** A file received via transferFile. `filePath` points at the local copy. */
  FILE(2);

  companion object {
    fun ofRaw(raw: Int): WearerEventKindDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** How (whether) this device can launch the companion app. */
enum class CompanionLaunchDto(val raw: Int) {
  /** RemoteActivityHelper: opens the companion in the foreground. */
  FOREGROUND(0),
  /** HealthKit workout session only (iOS -> watchOS). */
  WORKOUT_ONLY(1),
  /** The OS offers no way to launch the counterpart app. */
  NONE(2);

  companion object {
    fun ofRaw(raw: Int): CompanionLaunchDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Snapshot of the companion relationship.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CompanionStatusDto (
  val state: ConnectionStateDto,
  /** Reachable node ids (Android may have several; iOS has at most one). */
  val nodes: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CompanionStatusDto {
      val state = pigeonVar_list[0] as ConnectionStateDto
      val nodes = pigeonVar_list[1] as List<String>
      return CompanionStatusDto(state, nodes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
      nodes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CompanionStatusDto
    return MessagesPigeonUtils.deepEquals(this.state, other.state) && MessagesPigeonUtils.deepEquals(this.nodes, other.nodes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.state)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.nodes)
    return result
  }
}

/**
 * A message or data event crossing the device boundary.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class WearerEventDto (
  /** Unique id for at-least-once dedup across background replays. */
  val id: String,
  val kind: WearerEventKindDto,
  /** Application-defined routing path, e.g. '/workout/update'. */
  val path: String,
  val payload: ByteArray,
  val sourceNodeId: String,
  val timestampMillis: Long,
  /**
   * True when the event was received while no Flutter engine was attached
   * and is being replayed from the persistent queue.
   */
  val deliveredWhileDead: Boolean,
  /**
   * For [WearerEventKindDto.file] events: absolute path of the received
   * file (stored in the app's cache directory). Null for other kinds.
   */
  val filePath: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WearerEventDto {
      val id = pigeonVar_list[0] as String
      val kind = pigeonVar_list[1] as WearerEventKindDto
      val path = pigeonVar_list[2] as String
      val payload = pigeonVar_list[3] as ByteArray
      val sourceNodeId = pigeonVar_list[4] as String
      val timestampMillis = pigeonVar_list[5] as Long
      val deliveredWhileDead = pigeonVar_list[6] as Boolean
      val filePath = pigeonVar_list[7] as String?
      return WearerEventDto(id, kind, path, payload, sourceNodeId, timestampMillis, deliveredWhileDead, filePath)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      kind,
      path,
      payload,
      sourceNodeId,
      timestampMillis,
      deliveredWhileDead,
      filePath,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WearerEventDto
    return MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.kind, other.kind) && MessagesPigeonUtils.deepEquals(this.path, other.path) && MessagesPigeonUtils.deepEquals(this.payload, other.payload) && MessagesPigeonUtils.deepEquals(this.sourceNodeId, other.sourceNodeId) && MessagesPigeonUtils.deepEquals(this.timestampMillis, other.timestampMillis) && MessagesPigeonUtils.deepEquals(this.deliveredWhileDead, other.deliveredWhileDead) && MessagesPigeonUtils.deepEquals(this.filePath, other.filePath)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.kind)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.path)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.payload)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sourceNodeId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.timestampMillis)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.deliveredWhileDead)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.filePath)
    return result
  }
}

/**
 * What this device/pairing actually supports. Static OS facts plus the
 * dynamic ones (e.g. HealthKit availability); honest, never aspirational.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class WearerCapabilitiesDto (
  val message: Boolean,
  val request: Boolean,
  val syncData: Boolean,
  val transferData: Boolean,
  val transferFile: Boolean,
  /**
   * Bidirectional streams: native ChannelClient streams on Android,
   * sendMessage-framed emulation on iOS (needs a reachable counterpart).
   */
  val stream: Boolean,
  val companionLaunch: CompanionLaunchDto,
  /** transferCurrentComplicationUserInfo (iOS only). */
  val complicationPush: Boolean,
  /** Tile/complication re-render requests (Wear OS only). */
  val surfaceUpdate: Boolean,
  /**
   * Events delivered while the app is killed (listener service /
   * WatchConnectivity background launch).
   */
  val backgroundWake: Boolean,
  /**
   * Safe upper bound for a single sendMessage/sendRequest payload.
   * transferData has no limit (large payloads route through a file).
   */
  val maxMessageBytes: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WearerCapabilitiesDto {
      val message = pigeonVar_list[0] as Boolean
      val request = pigeonVar_list[1] as Boolean
      val syncData = pigeonVar_list[2] as Boolean
      val transferData = pigeonVar_list[3] as Boolean
      val transferFile = pigeonVar_list[4] as Boolean
      val stream = pigeonVar_list[5] as Boolean
      val companionLaunch = pigeonVar_list[6] as CompanionLaunchDto
      val complicationPush = pigeonVar_list[7] as Boolean
      val surfaceUpdate = pigeonVar_list[8] as Boolean
      val backgroundWake = pigeonVar_list[9] as Boolean
      val maxMessageBytes = pigeonVar_list[10] as Long
      return WearerCapabilitiesDto(message, request, syncData, transferData, transferFile, stream, companionLaunch, complicationPush, surfaceUpdate, backgroundWake, maxMessageBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      message,
      request,
      syncData,
      transferData,
      transferFile,
      stream,
      companionLaunch,
      complicationPush,
      surfaceUpdate,
      backgroundWake,
      maxMessageBytes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WearerCapabilitiesDto
    return MessagesPigeonUtils.deepEquals(this.message, other.message) && MessagesPigeonUtils.deepEquals(this.request, other.request) && MessagesPigeonUtils.deepEquals(this.syncData, other.syncData) && MessagesPigeonUtils.deepEquals(this.transferData, other.transferData) && MessagesPigeonUtils.deepEquals(this.transferFile, other.transferFile) && MessagesPigeonUtils.deepEquals(this.stream, other.stream) && MessagesPigeonUtils.deepEquals(this.companionLaunch, other.companionLaunch) && MessagesPigeonUtils.deepEquals(this.complicationPush, other.complicationPush) && MessagesPigeonUtils.deepEquals(this.surfaceUpdate, other.surfaceUpdate) && MessagesPigeonUtils.deepEquals(this.backgroundWake, other.backgroundWake) && MessagesPigeonUtils.deepEquals(this.maxMessageBytes, other.maxMessageBytes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.message)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.request)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.syncData)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.transferData)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.transferFile)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.stream)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.companionLaunch)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.complicationPush)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.surfaceUpdate)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.backgroundWake)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.maxMessageBytes)
    return result
  }
}

/**
 * A connected counterpart node.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class WearerNodeDto (
  val id: String,
  /** Human-readable device name where the platform provides one. */
  val displayName: String,
  /**
   * Android: Node.isNearby (direct Bluetooth/Wi-Fi link, not cloud).
   * iOS: mirrors reachability (the API has no separate notion).
   */
  val isNearby: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WearerNodeDto {
      val id = pigeonVar_list[0] as String
      val displayName = pigeonVar_list[1] as String
      val isNearby = pigeonVar_list[2] as Boolean
      return WearerNodeDto(id, displayName, isNearby)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      displayName,
      isNearby,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WearerNodeDto
    return MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.displayName, other.displayName) && MessagesPigeonUtils.deepEquals(this.isNearby, other.isNearby)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.displayName)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isNearby)
    return result
  }
}

/**
 * The counterpart device's vitals, served by a built-in handler on the
 * other side — works even before the counterpart app registers anything.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CounterpartStatusDto (
  /** 0–100, or -1 when the counterpart could not read it. */
  val batteryPercent: Long,
  val isCharging: Boolean,
  val model: String,
  val osVersion: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CounterpartStatusDto {
      val batteryPercent = pigeonVar_list[0] as Long
      val isCharging = pigeonVar_list[1] as Boolean
      val model = pigeonVar_list[2] as String
      val osVersion = pigeonVar_list[3] as String
      return CounterpartStatusDto(batteryPercent, isCharging, model, osVersion)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      batteryPercent,
      isCharging,
      model,
      osVersion,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CounterpartStatusDto
    return MessagesPigeonUtils.deepEquals(this.batteryPercent, other.batteryPercent) && MessagesPigeonUtils.deepEquals(this.isCharging, other.isCharging) && MessagesPigeonUtils.deepEquals(this.model, other.model) && MessagesPigeonUtils.deepEquals(this.osVersion, other.osVersion)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.batteryPercent)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isCharging)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.model)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.osVersion)
    return result
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ConnectionStateDto.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          WearerEventKindDto.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CompanionLaunchDto.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CompanionStatusDto.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WearerEventDto.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WearerCapabilitiesDto.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WearerNodeDto.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CounterpartStatusDto.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ConnectionStateDto -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is WearerEventKindDto -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is CompanionLaunchDto -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is CompanionStatusDto -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is WearerEventDto -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is WearerCapabilitiesDto -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is WearerNodeDto -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is CounterpartStatusDto -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Dart -> native.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface WearerLinkHostApi {
  /** Whether the wearable stack exists on this device at all. */
  fun isSupported(): Boolean
  fun getCompanionStatus(callback: (Result<CompanionStatusDto>) -> Unit)
  /**
   * Interactive message. Requires a reachable counterpart.
   * On Android sends to every reachable capable node, or only [nodeId]
   * when given; iOS has a single counterpart and ignores [nodeId].
   */
  fun sendMessage(path: String, payload: ByteArray, nodeId: String?, callback: (Result<Unit>) -> Unit)
  /**
   * Request/response round trip: resolves with the counterpart's reply
   * payload. Android: MessageClient.sendRequest RPC; iOS: sendMessage
   * reply payload. The counterpart must have a request handler
   * (setRequestHandler in Dart, onRequest in WearerLinkWatch); without one
   * the call fails with 'noHandler'.
   */
  fun sendRequest(path: String, payload: ByteArray, nodeId: String?, callback: (Result<ByteArray>) -> Unit)
  /**
   * Persistent state sync: DataClient item (Android) /
   * updateApplicationContext (iOS). Latest value per path wins.
   */
  fun syncData(path: String, payload: ByteArray, callback: (Result<Unit>) -> Unit)
  /**
   * Latest value the COUNTERPART synced for [path] (mirror of what
   * dataEvents delivered), or null if it never synced one.
   */
  fun readSyncData(path: String, callback: (Result<ByteArray?>) -> Unit)
  /**
   * Remove the value THIS device synced for [path] (the counterpart's own
   * value is theirs to delete).
   */
  fun deleteSyncData(path: String, callback: (Result<Unit>) -> Unit)
  /**
   * Latest value THIS device synced for [path] (mirror of what the
   * counterpart's readSyncData sees), or null.
   */
  fun readOwnSyncData(path: String, callback: (Result<ByteArray?>) -> Unit)
  /**
   * Every sync path currently stored under [prefix] — own and received
   * values combined. Powers the synced store's key listing.
   */
  fun listSyncPaths(prefix: String, callback: (Result<List<String>>) -> Unit)
  /**
   * Queued background transfer that survives unreachability:
   * DataClient with urgent flag (Android) / transferUserInfo (iOS).
   */
  fun transferData(path: String, payload: ByteArray, callback: (Result<Unit>) -> Unit)
  /**
   * Launch the companion app on the counterpart device.
   * Android: RemoteActivityHelper (both directions, foreground).
   * iOS phone->watch: HealthKit workout launch only; throws
   * 'unsupported' PlatformException otherwise.
   *
   * [route]/[argsJson] reach the launched app as a data event on the
   * reserved '/__wllaunch' path (queued, so it survives the launch
   * gap); on Android they are also appended to the launch URI.
   */
  fun launchCompanion(route: String?, argsJson: String?, callback: (Result<Unit>) -> Unit)
  /** Connected counterpart nodes with their platform facts. */
  fun getNodes(callback: (Result<List<WearerNodeDto>>) -> Unit)
  /**
   * The counterpart's vitals via the built-in '/__wlstatus' responder.
   * Requires a reachable counterpart running wearer_link >= 0.5.
   */
  fun getCounterpartStatus(nodeId: String?, callback: (Result<CounterpartStatusDto>) -> Unit)
  /**
   * Drain events persisted while the app was dead. Called by the Dart
   * facade on startup; each drained event is also removed from the store.
   */
  fun drainPendingEvents(callback: (Result<List<WearerEventDto>>) -> Unit)
  /**
   * Transfer the file at [filePath] to the counterpart (or only [nodeId]
   * on Android). Android: ChannelClient (needs a reachable capable node).
   * iOS: WCSession.transferFile (queued, survives unreachability).
   */
  fun transferFile(path: String, filePath: String, nodeId: String?, callback: (Result<Unit>) -> Unit)
  /**
   * Push fresh complication data to the watch face.
   * iOS: transferCurrentComplicationUserInfo (budgeted by watchOS — ~50/day;
   * over budget it silently degrades to a regular transfer).
   * Android: throws 'unsupported' — use syncData + requestSurfaceUpdate
   * inside the Wear OS app instead.
   */
  fun updateComplication(payload: ByteArray, callback: (Result<Unit>) -> Unit)
  /**
   * Ask the system to re-render this app's tile or complication after its
   * backing state changed. Wear OS only (call it inside the watch app);
   * [component] is the fully-qualified class name of the app's TileService
   * or complication data-source service. Throws 'unsupported' on iOS.
   */
  fun requestSurfaceUpdate(component: String, callback: (Result<Unit>) -> Unit)
  /**
   * Store the callback handles powering the headless background isolate.
   * [dispatcherHandle] is the plugin's entrypoint; [userHandle] the app's
   * top-level handler. Persisted natively so events that arrive while the
   * app is dead can start a Dart isolate and be handled immediately.
   */
  fun registerBackgroundHandler(dispatcherHandle: Long, userHandle: Long)
  /**
   * Stop launching the background isolate for dead-app events (they fall
   * back to the persistent queue only).
   */
  fun clearBackgroundHandler()
  /** What this device/pairing actually supports. */
  fun getCapabilities(): WearerCapabilitiesDto
  /**
   * While disabled, nothing is delivered to Dart or the background
   * isolate — every inbound event diverts to the persistent queue (same
   * path as a killed app; nothing is lost) and incoming streams are
   * rejected. Persisted across launches.
   */
  fun setEventDeliveryEnabled(enabled: Boolean)
  fun isEventDeliveryEnabled(): Boolean
  /**
   * Open a bidirectional stream to the counterpart; resolves with the
   * stream id once the counterpart accepted. Requires a reachable node.
   */
  fun openStream(path: String, nodeId: String?, callback: (Result<String>) -> Unit)
  /**
   * Write bytes to an open stream (chunked internally where the transport
   * needs it). Fails if the stream is closed.
   */
  fun sendStreamData(streamId: String, data: ByteArray, callback: (Result<Unit>) -> Unit)
  /** Close a stream (both directions). Idempotent. */
  fun closeStream(streamId: String, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by WearerLinkHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `WearerLinkHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: WearerLinkHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.isSupported$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isSupported())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.getCompanionStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getCompanionStatus{ result: Result<CompanionStatusDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.sendMessage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val payloadArg = args[1] as ByteArray
            val nodeIdArg = args[2] as String?
            api.sendMessage(pathArg, payloadArg, nodeIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.sendRequest$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val payloadArg = args[1] as ByteArray
            val nodeIdArg = args[2] as String?
            api.sendRequest(pathArg, payloadArg, nodeIdArg) { result: Result<ByteArray> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.syncData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val payloadArg = args[1] as ByteArray
            api.syncData(pathArg, payloadArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.readSyncData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            api.readSyncData(pathArg) { result: Result<ByteArray?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.deleteSyncData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            api.deleteSyncData(pathArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.readOwnSyncData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            api.readOwnSyncData(pathArg) { result: Result<ByteArray?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.listSyncPaths$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val prefixArg = args[0] as String
            api.listSyncPaths(prefixArg) { result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.transferData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val payloadArg = args[1] as ByteArray
            api.transferData(pathArg, payloadArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.launchCompanion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val routeArg = args[0] as String?
            val argsJsonArg = args[1] as String?
            api.launchCompanion(routeArg, argsJsonArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.getNodes$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getNodes{ result: Result<List<WearerNodeDto>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.getCounterpartStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nodeIdArg = args[0] as String?
            api.getCounterpartStatus(nodeIdArg) { result: Result<CounterpartStatusDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.drainPendingEvents$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.drainPendingEvents{ result: Result<List<WearerEventDto>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.transferFile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val filePathArg = args[1] as String
            val nodeIdArg = args[2] as String?
            api.transferFile(pathArg, filePathArg, nodeIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.updateComplication$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val payloadArg = args[0] as ByteArray
            api.updateComplication(payloadArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.requestSurfaceUpdate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val componentArg = args[0] as String
            api.requestSurfaceUpdate(componentArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.registerBackgroundHandler$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val dispatcherHandleArg = args[0] as Long
            val userHandleArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.registerBackgroundHandler(dispatcherHandleArg, userHandleArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.clearBackgroundHandler$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearBackgroundHandler()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.getCapabilities$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getCapabilities())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.setEventDeliveryEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setEventDeliveryEnabled(enabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.isEventDeliveryEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isEventDeliveryEnabled())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.openStream$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val nodeIdArg = args[1] as String?
            api.openStream(pathArg, nodeIdArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.sendStreamData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val streamIdArg = args[0] as String
            val dataArg = args[1] as ByteArray
            api.sendStreamData(streamIdArg, dataArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.closeStream$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val streamIdArg = args[0] as String
            api.closeStream(streamIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Native -> Dart.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class WearerLinkFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by WearerLinkFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  fun onMessage(eventArg: WearerEventDto, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.wearer_link.WearerLinkFlutterApi.onMessage$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /**
   * Request from the counterpart; the returned bytes are its reply.
   * Completing with an error rejects the request on the sender's side.
   */
  fun onRequest(eventArg: WearerEventDto, callback: (Result<ByteArray>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.wearer_link.WearerLinkFlutterApi.onRequest$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else if (it[0] == null) {
          callback(Result.failure(FlutterError("null-error", "Flutter api returned null value for non-null return value.", "")))
        } else {
          val output = it[0] as ByteArray
          callback(Result.success(output))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onDataChanged(eventArg: WearerEventDto, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.wearer_link.WearerLinkFlutterApi.onDataChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onFileReceived(eventArg: WearerEventDto, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.wearer_link.WearerLinkFlutterApi.onFileReceived$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onConnectionStateChanged(statusArg: CompanionStatusDto, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.wearer_link.WearerLinkFlutterApi.onConnectionStateChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(statusArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /**
   * A stream was opened — locally initiated (incoming=false, resolves the
   * pending openStream) or by the counterpart (incoming=true).
   */
  fun onStreamOpened(streamIdArg: String, pathArg: String, sourceNodeIdArg: String, incomingArg: Boolean, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.wearer_link.WearerLinkFlutterApi.onStreamOpened$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(streamIdArg, pathArg, sourceNodeIdArg, incomingArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onStreamData(streamIdArg: String, dataArg: ByteArray, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.wearer_link.WearerLinkFlutterApi.onStreamData$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(streamIdArg, dataArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** The stream ended; [error] is null for an orderly close. */
  fun onStreamClosed(streamIdArg: String, errorArg: String?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.wearer_link.WearerLinkFlutterApi.onStreamClosed$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(streamIdArg, errorArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
/**
 * Dart -> native, background isolate only.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface WearerLinkBackgroundHostApi {
  /**
   * Handshake from the freshly-started background isolate. Returns the raw
   * callback handle of the user's registered handler; after this returns,
   * the native side starts delivering queued events.
   */
  fun backgroundReady(): Long

  companion object {
    /** The codec used by WearerLinkBackgroundHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `WearerLinkBackgroundHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: WearerLinkBackgroundHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wearer_link.WearerLinkBackgroundHostApi.backgroundReady$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.backgroundReady())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Native -> Dart, background isolate only. The completion of
 * [onBackgroundEvent] is the delivery ack: the native side removes the
 * event from the persistent queue only after the Dart future completes.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class WearerLinkBackgroundFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by WearerLinkBackgroundFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  fun onBackgroundEvent(eventArg: WearerEventDto, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.wearer_link.WearerLinkBackgroundFlutterApi.onBackgroundEvent$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
