// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsMessages(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashMessages(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsMessages(lhsKey, rhsKey) {
          if deepEqualsMessages(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsMessages(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashMessages(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashMessages(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashMessages(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashMessages(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashMessages(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Reachability of the paired wearable/phone counterpart.
enum ConnectionStateDto: Int {
  /// Platform stack unavailable (no Play Services / WCSession unsupported).
  case unsupported = 0
  /// No counterpart device is paired.
  case unpaired = 1
  /// Paired, companion app not installed on the counterpart.
  case appNotInstalled = 2
  /// Paired and installed, but not currently reachable (e.g. Bluetooth off).
  case unreachable = 3
  /// Counterpart is reachable for interactive messages.
  case reachable = 4
}

/// How an event crossed the boundary.
enum WearerEventKindDto: Int {
  /// Interactive message.
  case message = 0
  /// Synced or transferred data.
  case data = 1
}

/// Snapshot of the companion relationship.
///
/// Generated class from Pigeon that represents data sent in messages.
struct CompanionStatusDto: Hashable {
  var state: ConnectionStateDto
  /// Reachable node ids (Android may have several; iOS has at most one).
  var nodes: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CompanionStatusDto? {
    let state = pigeonVar_list[0] as! ConnectionStateDto
    let nodes = pigeonVar_list[1] as! [String]

    return CompanionStatusDto(
      state: state,
      nodes: nodes
    )
  }
  func toList() -> [Any?] {
    return [
      state,
      nodes,
    ]
  }
  static func == (lhs: CompanionStatusDto, rhs: CompanionStatusDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.state, rhs.state) && deepEqualsMessages(lhs.nodes, rhs.nodes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CompanionStatusDto")
    deepHashMessages(value: state, hasher: &hasher)
    deepHashMessages(value: nodes, hasher: &hasher)
  }
}

/// A message or data event crossing the device boundary.
///
/// Generated class from Pigeon that represents data sent in messages.
struct WearerEventDto: Hashable {
  /// Unique id for at-least-once dedup across background replays.
  var id: String
  var kind: WearerEventKindDto
  /// Application-defined routing path, e.g. '/workout/update'.
  var path: String
  var payload: FlutterStandardTypedData
  var sourceNodeId: String
  var timestampMillis: Int64
  /// True when the event was received while no Flutter engine was attached
  /// and is being replayed from the persistent queue.
  var deliveredWhileDead: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WearerEventDto? {
    let id = pigeonVar_list[0] as! String
    let kind = pigeonVar_list[1] as! WearerEventKindDto
    let path = pigeonVar_list[2] as! String
    let payload = pigeonVar_list[3] as! FlutterStandardTypedData
    let sourceNodeId = pigeonVar_list[4] as! String
    let timestampMillis = pigeonVar_list[5] as! Int64
    let deliveredWhileDead = pigeonVar_list[6] as! Bool

    return WearerEventDto(
      id: id,
      kind: kind,
      path: path,
      payload: payload,
      sourceNodeId: sourceNodeId,
      timestampMillis: timestampMillis,
      deliveredWhileDead: deliveredWhileDead
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      kind,
      path,
      payload,
      sourceNodeId,
      timestampMillis,
      deliveredWhileDead,
    ]
  }
  static func == (lhs: WearerEventDto, rhs: WearerEventDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.id, rhs.id) && deepEqualsMessages(lhs.kind, rhs.kind) && deepEqualsMessages(lhs.path, rhs.path) && deepEqualsMessages(lhs.payload, rhs.payload) && deepEqualsMessages(lhs.sourceNodeId, rhs.sourceNodeId) && deepEqualsMessages(lhs.timestampMillis, rhs.timestampMillis) && deepEqualsMessages(lhs.deliveredWhileDead, rhs.deliveredWhileDead)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WearerEventDto")
    deepHashMessages(value: id, hasher: &hasher)
    deepHashMessages(value: kind, hasher: &hasher)
    deepHashMessages(value: path, hasher: &hasher)
    deepHashMessages(value: payload, hasher: &hasher)
    deepHashMessages(value: sourceNodeId, hasher: &hasher)
    deepHashMessages(value: timestampMillis, hasher: &hasher)
    deepHashMessages(value: deliveredWhileDead, hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ConnectionStateDto(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WearerEventKindDto(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return CompanionStatusDto.fromList(self.readValue() as! [Any?])
    case 132:
      return WearerEventDto.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ConnectionStateDto {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? WearerEventKindDto {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? CompanionStatusDto {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? WearerEventDto {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Dart -> native.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol WearerLinkHostApi {
  /// Whether the wearable stack exists on this device at all.
  func isSupported() throws -> Bool
  func getCompanionStatus(completion: @escaping (Result<CompanionStatusDto, Error>) -> Void)
  /// Interactive message. Requires a reachable counterpart.
  /// On Android sends to every reachable node advertising the capability.
  func sendMessage(path: String, payload: FlutterStandardTypedData, completion: @escaping (Result<Void, Error>) -> Void)
  /// Persistent state sync: DataClient item (Android) /
  /// updateApplicationContext (iOS). Latest value per path wins.
  func syncData(path: String, payload: FlutterStandardTypedData, completion: @escaping (Result<Void, Error>) -> Void)
  /// Queued background transfer that survives unreachability:
  /// DataClient with urgent flag (Android) / transferUserInfo (iOS).
  func transferData(path: String, payload: FlutterStandardTypedData, completion: @escaping (Result<Void, Error>) -> Void)
  /// Launch the companion app on the counterpart device.
  /// Android: RemoteActivityHelper (both directions, foreground).
  /// iOS phone->watch: HealthKit workout launch only; throws
  /// 'unsupported' PlatformException otherwise.
  func launchCompanion(completion: @escaping (Result<Void, Error>) -> Void)
  /// Drain events persisted while the app was dead. Called by the Dart
  /// facade on startup; each drained event is also removed from the store.
  func drainPendingEvents(completion: @escaping (Result<[WearerEventDto], Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class WearerLinkHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `WearerLinkHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: WearerLinkHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Whether the wearable stack exists on this device at all.
    let isSupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.isSupported\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isSupportedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isSupported()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isSupportedChannel.setMessageHandler(nil)
    }
    let getCompanionStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.getCompanionStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCompanionStatusChannel.setMessageHandler { _, reply in
        api.getCompanionStatus { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getCompanionStatusChannel.setMessageHandler(nil)
    }
    /// Interactive message. Requires a reachable counterpart.
    /// On Android sends to every reachable node advertising the capability.
    let sendMessageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.sendMessage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendMessageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        let payloadArg = args[1] as! FlutterStandardTypedData
        api.sendMessage(path: pathArg, payload: payloadArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendMessageChannel.setMessageHandler(nil)
    }
    /// Persistent state sync: DataClient item (Android) /
    /// updateApplicationContext (iOS). Latest value per path wins.
    let syncDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.syncData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      syncDataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        let payloadArg = args[1] as! FlutterStandardTypedData
        api.syncData(path: pathArg, payload: payloadArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      syncDataChannel.setMessageHandler(nil)
    }
    /// Queued background transfer that survives unreachability:
    /// DataClient with urgent flag (Android) / transferUserInfo (iOS).
    let transferDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.transferData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      transferDataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        let payloadArg = args[1] as! FlutterStandardTypedData
        api.transferData(path: pathArg, payload: payloadArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      transferDataChannel.setMessageHandler(nil)
    }
    /// Launch the companion app on the counterpart device.
    /// Android: RemoteActivityHelper (both directions, foreground).
    /// iOS phone->watch: HealthKit workout launch only; throws
    /// 'unsupported' PlatformException otherwise.
    let launchCompanionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.launchCompanion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      launchCompanionChannel.setMessageHandler { _, reply in
        api.launchCompanion { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      launchCompanionChannel.setMessageHandler(nil)
    }
    /// Drain events persisted while the app was dead. Called by the Dart
    /// facade on startup; each drained event is also removed from the store.
    let drainPendingEventsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.wearer_link.WearerLinkHostApi.drainPendingEvents\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      drainPendingEventsChannel.setMessageHandler { _, reply in
        api.drainPendingEvents { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      drainPendingEventsChannel.setMessageHandler(nil)
    }
  }
}
/// Native -> Dart.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol WearerLinkFlutterApiProtocol {
  func onMessage(event eventArg: WearerEventDto, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onDataChanged(event eventArg: WearerEventDto, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onConnectionStateChanged(status statusArg: CompanionStatusDto, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class WearerLinkFlutterApi: WearerLinkFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onMessage(event eventArg: WearerEventDto, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.wearer_link.WearerLinkFlutterApi.onMessage\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onDataChanged(event eventArg: WearerEventDto, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.wearer_link.WearerLinkFlutterApi.onDataChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onConnectionStateChanged(status statusArg: CompanionStatusDto, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.wearer_link.WearerLinkFlutterApi.onConnectionStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([statusArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
