import 'dart:typed_data';

import 'package:meta/meta.dart';

import 'messages.g.dart';

/// Internal: field-preserving copy for the wire DTO.
///
/// The DTO is regenerated by Pigeon and has no copyWith, so every hand-written
/// copy is a place a newly added field can be silently dropped — which is
/// exactly how the decrypt rebuild lost the identity fields. Route copies
/// through here instead.
@internal
extension WearerEventDtoCopy on WearerEventDto {
  /// Returns a copy with the named fields replaced.
  @internal
  WearerEventDto copyWith({
    Uint8List? payload,
    bool? deliveredWhileDead,
  }) =>
      WearerEventDto(
        id: id,
        kind: kind,
        path: path,
        payload: payload ?? this.payload,
        sourceNodeId: sourceNodeId,
        timestampMillis: timestampMillis,
        deliveredWhileDead: deliveredWhileDead ?? this.deliveredWhileDead,
        filePath: filePath,
        linkId: linkId,
        protocolVersion: protocolVersion,
      );
}
