// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Reachability of the paired wearable/phone counterpart.
enum ConnectionStateDto {
  /// Platform stack unavailable (no Play Services / WCSession unsupported).
  unsupported,
  /// No counterpart device is paired.
  unpaired,
  /// Paired, companion app not installed on the counterpart.
  appNotInstalled,
  /// Paired and installed, but not currently reachable (e.g. Bluetooth off).
  unreachable,
  /// Counterpart is reachable for interactive messages.
  reachable,
}

/// How an event crossed the boundary.
enum WearerEventKindDto {
  /// Interactive message.
  message,
  /// Synced or transferred data.
  data,
  /// A file received via transferFile. `filePath` points at the local copy.
  file,
}

/// How (whether) this device can launch the companion app.
enum CompanionLaunchDto {
  /// RemoteActivityHelper: opens the companion in the foreground.
  foreground,
  /// HealthKit workout session only (iOS -> watchOS).
  workoutOnly,
  /// The OS offers no way to launch the counterpart app.
  none,
}

/// Snapshot of the companion relationship.
class CompanionStatusDto {
  CompanionStatusDto({
    required this.state,
    required this.nodes,
  });

  ConnectionStateDto state;

  /// Reachable node ids (Android may have several; iOS has at most one).
  List<String> nodes;

  List<Object?> _toList() {
    return <Object?>[
      state,
      nodes,
    ];
  }

  Object encode() {
    return _toList();  }

  static CompanionStatusDto decode(Object result) {
    result as List<Object?>;
    return CompanionStatusDto(
      state: result[0]! as ConnectionStateDto,
      nodes: (result[1]! as List<Object?>).cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CompanionStatusDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(state, other.state) && _deepEquals(nodes, other.nodes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// A message or data event crossing the device boundary.
class WearerEventDto {
  WearerEventDto({
    required this.id,
    required this.kind,
    required this.path,
    required this.payload,
    required this.sourceNodeId,
    required this.timestampMillis,
    required this.deliveredWhileDead,
    this.filePath,
  });

  /// Unique id for at-least-once dedup across background replays.
  String id;

  WearerEventKindDto kind;

  /// Application-defined routing path, e.g. '/workout/update'.
  String path;

  Uint8List payload;

  String sourceNodeId;

  int timestampMillis;

  /// True when the event was received while no Flutter engine was attached
  /// and is being replayed from the persistent queue.
  bool deliveredWhileDead;

  /// For [WearerEventKindDto.file] events: absolute path of the received
  /// file (stored in the app's cache directory). Null for other kinds.
  String? filePath;

  List<Object?> _toList() {
    return <Object?>[
      id,
      kind,
      path,
      payload,
      sourceNodeId,
      timestampMillis,
      deliveredWhileDead,
      filePath,
    ];
  }

  Object encode() {
    return _toList();  }

  static WearerEventDto decode(Object result) {
    result as List<Object?>;
    return WearerEventDto(
      id: result[0]! as String,
      kind: result[1]! as WearerEventKindDto,
      path: result[2]! as String,
      payload: result[3]! as Uint8List,
      sourceNodeId: result[4]! as String,
      timestampMillis: result[5]! as int,
      deliveredWhileDead: result[6]! as bool,
      filePath: result[7] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WearerEventDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(kind, other.kind) && _deepEquals(path, other.path) && _deepEquals(payload, other.payload) && _deepEquals(sourceNodeId, other.sourceNodeId) && _deepEquals(timestampMillis, other.timestampMillis) && _deepEquals(deliveredWhileDead, other.deliveredWhileDead) && _deepEquals(filePath, other.filePath);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// What this device/pairing actually supports. Static OS facts plus the
/// dynamic ones (e.g. HealthKit availability); honest, never aspirational.
class WearerCapabilitiesDto {
  WearerCapabilitiesDto({
    required this.message,
    required this.request,
    required this.syncData,
    required this.transferData,
    required this.transferFile,
    required this.stream,
    required this.companionLaunch,
    required this.complicationPush,
    required this.surfaceUpdate,
    required this.backgroundWake,
    required this.maxMessageBytes,
  });

  bool message;

  bool request;

  bool syncData;

  bool transferData;

  bool transferFile;

  /// Bidirectional streams: native ChannelClient streams on Android,
  /// sendMessage-framed emulation on iOS (needs a reachable counterpart).
  bool stream;

  CompanionLaunchDto companionLaunch;

  /// transferCurrentComplicationUserInfo (iOS only).
  bool complicationPush;

  /// Tile/complication re-render requests (Wear OS only).
  bool surfaceUpdate;

  /// Events delivered while the app is killed (listener service /
  /// WatchConnectivity background launch).
  bool backgroundWake;

  /// Safe upper bound for a single sendMessage/sendRequest payload.
  /// transferData has no limit (large payloads route through a file).
  int maxMessageBytes;

  List<Object?> _toList() {
    return <Object?>[
      message,
      request,
      syncData,
      transferData,
      transferFile,
      stream,
      companionLaunch,
      complicationPush,
      surfaceUpdate,
      backgroundWake,
      maxMessageBytes,
    ];
  }

  Object encode() {
    return _toList();  }

  static WearerCapabilitiesDto decode(Object result) {
    result as List<Object?>;
    return WearerCapabilitiesDto(
      message: result[0]! as bool,
      request: result[1]! as bool,
      syncData: result[2]! as bool,
      transferData: result[3]! as bool,
      transferFile: result[4]! as bool,
      stream: result[5]! as bool,
      companionLaunch: result[6]! as CompanionLaunchDto,
      complicationPush: result[7]! as bool,
      surfaceUpdate: result[8]! as bool,
      backgroundWake: result[9]! as bool,
      maxMessageBytes: result[10]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WearerCapabilitiesDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(message, other.message) && _deepEquals(request, other.request) && _deepEquals(syncData, other.syncData) && _deepEquals(transferData, other.transferData) && _deepEquals(transferFile, other.transferFile) && _deepEquals(stream, other.stream) && _deepEquals(companionLaunch, other.companionLaunch) && _deepEquals(complicationPush, other.complicationPush) && _deepEquals(surfaceUpdate, other.surfaceUpdate) && _deepEquals(backgroundWake, other.backgroundWake) && _deepEquals(maxMessageBytes, other.maxMessageBytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// A connected counterpart node.
class WearerNodeDto {
  WearerNodeDto({
    required this.id,
    required this.displayName,
    required this.isNearby,
  });

  String id;

  /// Human-readable device name where the platform provides one.
  String displayName;

  /// Android: Node.isNearby (direct Bluetooth/Wi-Fi link, not cloud).
  /// iOS: mirrors reachability (the API has no separate notion).
  bool isNearby;

  List<Object?> _toList() {
    return <Object?>[
      id,
      displayName,
      isNearby,
    ];
  }

  Object encode() {
    return _toList();  }

  static WearerNodeDto decode(Object result) {
    result as List<Object?>;
    return WearerNodeDto(
      id: result[0]! as String,
      displayName: result[1]! as String,
      isNearby: result[2]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WearerNodeDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(displayName, other.displayName) && _deepEquals(isNearby, other.isNearby);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// The counterpart device's vitals, served by a built-in handler on the
/// other side — works even before the counterpart app registers anything.
class CounterpartStatusDto {
  CounterpartStatusDto({
    required this.batteryPercent,
    required this.isCharging,
    required this.model,
    required this.osVersion,
  });

  /// 0–100, or -1 when the counterpart could not read it.
  int batteryPercent;

  bool isCharging;

  String model;

  String osVersion;

  List<Object?> _toList() {
    return <Object?>[
      batteryPercent,
      isCharging,
      model,
      osVersion,
    ];
  }

  Object encode() {
    return _toList();  }

  static CounterpartStatusDto decode(Object result) {
    result as List<Object?>;
    return CounterpartStatusDto(
      batteryPercent: result[0]! as int,
      isCharging: result[1]! as bool,
      model: result[2]! as String,
      osVersion: result[3]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CounterpartStatusDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(batteryPercent, other.batteryPercent) && _deepEquals(isCharging, other.isCharging) && _deepEquals(model, other.model) && _deepEquals(osVersion, other.osVersion);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is ConnectionStateDto) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is WearerEventKindDto) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is CompanionLaunchDto) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is CompanionStatusDto) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is WearerEventDto) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is WearerCapabilitiesDto) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is WearerNodeDto) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is CounterpartStatusDto) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : ConnectionStateDto.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : WearerEventKindDto.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : CompanionLaunchDto.values[value];
      case 132:
        return CompanionStatusDto.decode(readValue(buffer)!);
      case 133:
        return WearerEventDto.decode(readValue(buffer)!);
      case 134:
        return WearerCapabilitiesDto.decode(readValue(buffer)!);
      case 135:
        return WearerNodeDto.decode(readValue(buffer)!);
      case 136:
        return CounterpartStatusDto.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Dart -> native.
class WearerLinkHostApi {
  /// Constructor for [WearerLinkHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  WearerLinkHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Whether the wearable stack exists on this device at all.
  Future<bool> isSupported() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.wearer_link.WearerLinkHostApi.isSupported$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<CompanionStatusDto> getCompanionStatus() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.wearer_link.WearerLinkHostApi.getCompanionStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as CompanionStatusDto;
  }

  /// Interactive message. Requires a reachable counterpart.
  /// On Android sends to every reachable capable node, or only [nodeId]
  /// when given; iOS has a single counterpart and ignores [nodeId].
  Future<void> sendMessage(String path, Uint8List payload, String? nodeId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.wearer_link.WearerLinkHostApi.sendMessage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[path, payload, nodeId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Request/response round trip: resolves with the counterpart's reply
  /// payload. Android: MessageClient.sendRequest RPC; iOS: sendMessage
  /// reply payload. The counterpart must have a request handler
  /// (setRequestHandler in Dart, onRequest in WearerLinkWatch); without one
  /// the call fails with 'noHandler'.
  Future<Uint8List> sendRequest(String path, Uint8List payload, String? nodeId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.wearer_link.WearerLinkHostApi.sendRequest$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[path, payload, nodeId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as Uint8List;
  }

  /// Persistent state sync: DataClient item (Android) /
  /// updateApplicationContext (iOS). Latest value per path wins.
  Future<void> syncData(String path, Uint8List payload) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.wearer_link.WearerLinkHostApi.syncData$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[path, payload]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Latest value the COUNTERPART synced for [path] (mirror of what
  /// dataEvents delivered), or null if it never synced one.
  Future<Uint8List?> readSyncData(String path) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.wearer_link.WearerLinkHostApi.readSyncData$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[path]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as Uint8List?;
  }

  /// Remove the value THIS device synced for [path] (the counterpart's own
  /// value is theirs to delete).
  Future<void> deleteSyncData(String path) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.wearer_link.WearerLinkHostApi.deleteSyncData$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[path]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Latest value THIS device synced for [path] (mirror of what the
  /// counterpart's readSyncData sees), or null.
  Future<Uint8List?> readOwnSyncData(String path) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.wearer_link.WearerLinkHostApi.readOwnSyncData$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[path]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as Uint8List?;
  }

  /// Every sync path currently stored under [prefix] — own and received
  /// values combined. Powers the synced store's key listing.
  Future<List<String>> listSyncPaths(String prefix) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.wearer_link.WearerLinkHostApi.listSyncPaths$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[prefix]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }

  /// Queued background transfer that survives unreachability:
  /// DataClient with urgent flag (Android) / transferUserInfo (iOS).
  Future<void> transferData(String path, Uint8List payload) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.wearer_link.WearerLinkHostApi.transferData$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[path, payload]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Launch the companion app on the counterpart device.
  /// Android: RemoteActivityHelper (both directions, foreground).
  /// iOS phone->watch: HealthKit workout launch only; throws
  /// 'unsupported' PlatformException otherwise.
  ///
  /// [route]/[argsJson] reach the launched app as a data event on the
  /// reserved '/__wllaunch' path (queued, so it survives the launch
  /// gap); on Android they are also appended to the launch URI.
  Future<void> launchCompanion(String? route, String? argsJson) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.wearer_link.WearerLinkHostApi.launchCompanion$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[route, argsJson]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Connected counterpart nodes with their platform facts.
  Future<List<WearerNodeDto>> getNodes() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.wearer_link.WearerLinkHostApi.getNodes$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<WearerNodeDto>();
  }

  /// The counterpart's vitals via the built-in '/__wlstatus' responder.
  /// Requires a reachable counterpart running wearer_link >= 0.5.
  Future<CounterpartStatusDto> getCounterpartStatus(String? nodeId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.wearer_link.WearerLinkHostApi.getCounterpartStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[nodeId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as CounterpartStatusDto;
  }

  /// Drain events persisted while the app was dead. Called by the Dart
  /// facade on startup; each drained event is also removed from the store.
  Future<List<WearerEventDto>> drainPendingEvents() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.wearer_link.WearerLinkHostApi.drainPendingEvents$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<WearerEventDto>();
  }

  /// Transfer the file at [filePath] to the counterpart (or only [nodeId]
  /// on Android). Android: ChannelClient (needs a reachable capable node).
  /// iOS: WCSession.transferFile (queued, survives unreachability).
  Future<void> transferFile(String path, String filePath, String? nodeId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.wearer_link.WearerLinkHostApi.transferFile$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[path, filePath, nodeId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Push fresh complication data to the watch face.
  /// iOS: transferCurrentComplicationUserInfo (budgeted by watchOS — ~50/day;
  /// over budget it silently degrades to a regular transfer).
  /// Android: throws 'unsupported' — use syncData + requestSurfaceUpdate
  /// inside the Wear OS app instead.
  Future<void> updateComplication(Uint8List payload) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.wearer_link.WearerLinkHostApi.updateComplication$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[payload]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Ask the system to re-render this app's tile or complication after its
  /// backing state changed. Wear OS only (call it inside the watch app);
  /// [component] is the fully-qualified class name of the app's TileService
  /// or complication data-source service. Throws 'unsupported' on iOS.
  Future<void> requestSurfaceUpdate(String component) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.wearer_link.WearerLinkHostApi.requestSurfaceUpdate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[component]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Store the callback handles powering the headless background isolate.
  /// [dispatcherHandle] is the plugin's entrypoint; [userHandle] the app's
  /// top-level handler. Persisted natively so events that arrive while the
  /// app is dead can start a Dart isolate and be handled immediately.
  Future<void> registerBackgroundHandler(int dispatcherHandle, int userHandle) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.wearer_link.WearerLinkHostApi.registerBackgroundHandler$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[dispatcherHandle, userHandle]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Stop launching the background isolate for dead-app events (they fall
  /// back to the persistent queue only).
  Future<void> clearBackgroundHandler() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.wearer_link.WearerLinkHostApi.clearBackgroundHandler$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// What this device/pairing actually supports.
  Future<WearerCapabilitiesDto> getCapabilities() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.wearer_link.WearerLinkHostApi.getCapabilities$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as WearerCapabilitiesDto;
  }

  /// While disabled, nothing is delivered to Dart or the background
  /// isolate — every inbound event diverts to the persistent queue (same
  /// path as a killed app; nothing is lost) and incoming streams are
  /// rejected. Persisted across launches.
  Future<void> setEventDeliveryEnabled(bool enabled) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.wearer_link.WearerLinkHostApi.setEventDeliveryEnabled$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[enabled]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<bool> isEventDeliveryEnabled() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.wearer_link.WearerLinkHostApi.isEventDeliveryEnabled$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Open a bidirectional stream to the counterpart; resolves with the
  /// stream id once the counterpart accepted. Requires a reachable node.
  Future<String> openStream(String path, String? nodeId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.wearer_link.WearerLinkHostApi.openStream$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[path, nodeId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  /// Write bytes to an open stream (chunked internally where the transport
  /// needs it). Fails if the stream is closed.
  Future<void> sendStreamData(String streamId, Uint8List data) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.wearer_link.WearerLinkHostApi.sendStreamData$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[streamId, data]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Close a stream (both directions). Idempotent.
  Future<void> closeStream(String streamId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.wearer_link.WearerLinkHostApi.closeStream$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[streamId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

/// Native -> Dart.
abstract class WearerLinkFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onMessage(WearerEventDto event);

  /// Request from the counterpart; the returned bytes are its reply.
  /// Completing with an error rejects the request on the sender's side.
  Future<Uint8List> onRequest(WearerEventDto event);

  void onDataChanged(WearerEventDto event);

  void onFileReceived(WearerEventDto event);

  void onConnectionStateChanged(CompanionStatusDto status);

  /// A stream was opened — locally initiated (incoming=false, resolves the
  /// pending openStream) or by the counterpart (incoming=true).
  void onStreamOpened(String streamId, String path, String sourceNodeId, bool incoming);

  void onStreamData(String streamId, Uint8List data);

  /// The stream ended; [error] is null for an orderly close.
  void onStreamClosed(String streamId, String? error);

  static void setUp(WearerLinkFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.wearer_link.WearerLinkFlutterApi.onMessage$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final WearerEventDto arg_event = args[0]! as WearerEventDto;
          try {
            api.onMessage(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.wearer_link.WearerLinkFlutterApi.onRequest$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final WearerEventDto arg_event = args[0]! as WearerEventDto;
          try {
            final Uint8List output = await api.onRequest(arg_event);
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.wearer_link.WearerLinkFlutterApi.onDataChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final WearerEventDto arg_event = args[0]! as WearerEventDto;
          try {
            api.onDataChanged(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.wearer_link.WearerLinkFlutterApi.onFileReceived$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final WearerEventDto arg_event = args[0]! as WearerEventDto;
          try {
            api.onFileReceived(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.wearer_link.WearerLinkFlutterApi.onConnectionStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final CompanionStatusDto arg_status = args[0]! as CompanionStatusDto;
          try {
            api.onConnectionStateChanged(arg_status);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.wearer_link.WearerLinkFlutterApi.onStreamOpened$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_streamId = args[0]! as String;
          final String arg_path = args[1]! as String;
          final String arg_sourceNodeId = args[2]! as String;
          final bool arg_incoming = args[3]! as bool;
          try {
            api.onStreamOpened(arg_streamId, arg_path, arg_sourceNodeId, arg_incoming);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.wearer_link.WearerLinkFlutterApi.onStreamData$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_streamId = args[0]! as String;
          final Uint8List arg_data = args[1]! as Uint8List;
          try {
            api.onStreamData(arg_streamId, arg_data);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.wearer_link.WearerLinkFlutterApi.onStreamClosed$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_streamId = args[0]! as String;
          final String? arg_error = args[1] as String?;
          try {
            api.onStreamClosed(arg_streamId, arg_error);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}

/// Dart -> native, background isolate only.
class WearerLinkBackgroundHostApi {
  /// Constructor for [WearerLinkBackgroundHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  WearerLinkBackgroundHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Handshake from the freshly-started background isolate. Returns the raw
  /// callback handle of the user's registered handler; after this returns,
  /// the native side starts delivering queued events.
  Future<int> backgroundReady() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.wearer_link.WearerLinkBackgroundHostApi.backgroundReady$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }
}

/// Native -> Dart, background isolate only. The completion of
/// [onBackgroundEvent] is the delivery ack: the native side removes the
/// event from the persistent queue only after the Dart future completes.
abstract class WearerLinkBackgroundFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  Future<void> onBackgroundEvent(WearerEventDto event);

  static void setUp(WearerLinkBackgroundFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.wearer_link.WearerLinkBackgroundFlutterApi.onBackgroundEvent$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final WearerEventDto arg_event = args[0]! as WearerEventDto;
          try {
            await api.onBackgroundEvent(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
